set MAKE=nmake
perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
IF %ERRORLEVEL% NEQ 0 exit /B 1
%MAKE%
IF %ERRORLEVEL% NEQ 0 exit /B 1
%MAKE% test
IF %ERRORLEVEL% NEQ 0 exit /B 1
%MAKE% install VERBINST=1
IF %ERRORLEVEL% NEQ 0 exit /B 1
