{% set name = "perl-sys-cpu" %}
{% set version = "0.61" %}
{% set hash = "250a86b79c231001c4ae71d2f66428092a4fbb2070971acafd471aa49739c9e4" %}
 
package:
    name: {{ name }}
    version: {{ version }}
    
source:
    url: https://cpan.metacpan.org/authors/id/M/MZ/MZSANFORD/Sys-CPU-{{ version }}.tar.gz
    sha256: {{ hash }}
    
build:
    number: 3
    skip: true  # [win or osx]

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - perl
    run:
        - perl
        
test:
    imports:
        - Sys::CPU
about:
    home: http://metacpan.org/pod/Sys::CPU
    license: perl5
    summary: Perl extension for getting CPU information. Currently only number of
        CPU's supported.

extra:
    recipe-maintainers:
        - jupollet
        
