{% set version = "0.61" %}
{% set sha256 = "250a86b79c231001c4ae71d2f66428092a4fbb2070971acafd471aa49739c9e4" %}
 
package:
  name: perl-sys-cpu
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MZ/MZSANFORD/Sys-CPU-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - perl
  run:
    - perl

test:
  imports:
    - Sys::CPU

about:
  home: http://metacpan.org/pod/Sys::CPU
  license: perl5
  summary: >
    Perl extension for getting CPU information. Currently only number of
    CPU's supported.

extra:
  recipe-maintainers:
    - jupollet
