{% set version = "0.61" %}
{% set sha256 = "250a86b79c231001c4ae71d2f66428092a4fbb2070971acafd471aa49739c9e4" %}
 
package:
  name: perl-sys-cpu
  version: {{ version }}

source:
  - url: https://cpan.metacpan.org/authors/id/M/MZ/MZSANFORD/Sys-CPU-{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: https://raw.githubusercontent.com/Perl/perl5/v5.32.1/Copying
    sha256: d77d235e41d54594865151f4751e835c5a82322b0e87ace266567c3391a4b912
  - url: https://raw.githubusercontent.com/Perl/perl5/v5.32.1/Artistic
    sha256: dd90d4f42e4dcadf5a7c09eea0189d93c7b37ae560c91f0f6d5233ed3b9292a2

build:
  number: 2
  skip: true  # [win or osx]
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - perl
  run:
    - perl

test:
  imports:
    - Sys::CPU

about:
  home: http://metacpan.org/pod/Sys::CPU
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - Artistic
    - Copying
  summary: >
    Perl extension for getting CPU information. Currently only number of
    CPU's supported.

extra:
  recipe-maintainers:
    - jupollet
