travis:
  secure:
    BINSTAR_TOKEN: Kg55fLVqg5gi1K062HGHZ+jRkeLW1obOIOOQP5Aaa5myW8La8nCGVE8emZcrhNPuzpD67iy5p0HYfhVJzbUtJCNO5hIOOkyLbu5Y+c8ixxrXNmuuqjEL5Hc7g6hU7pL7JKPbEM+DcFSFqt84+9uX4fLlnR2uxKLgmMPGcA6C7NpWV0hZ8hkCUivy5tXLeSbXbJPOyDNwxh3Nn4KuZrpq+AZxTuWkSzHxDaJwG4Fo1y1gLyvnhiQdg/8E9uCTui+wrcR6iRBEHhBGnlABz7yFd19GIOjGbhoRaMzlowK0TizmQBS0R1SW3LwYqyGbWrXuvU9y/ZoD95o674aXc7FXPSfvg8DUK3iIaVVWpYufGq3Pu5F+zF4P/Dajc23Tl2cijlr938Fp7aJ0UewMZKnDKKScYXz0+tUyRwyOdQZwsZCGEhTKDj6o7J2V6HRyKBj5HRdSMx7Z5ZXsYziCy/PrVqXQDmSf3Rp228IjWwXdDX6mNHcbghmYtViRgNXtARFSH1CtVGCVen5EieExmfBngIVafKP3tFLQEWSudUcMspTMKkKD+Ju7t2zSMAR0YtH2nRPioxEdaiyzMTGjJI/ocqFVuWw8Zc933m86vzQq2n7V5UGHckMta6JtkDEsRg8NWRhGgGOjVP2D6PXaPKuAkodUbvo3M3t9RLCv+xz1G9s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
