travis:
  secure:
    BINSTAR_TOKEN: HryVbMtqdQVXwIDBieMO3gc5hgtWFwp5ZGK1yp/1ZwWz2mjuJ/zLZ+HWUJgiz4ef97Gw4Or81q2p/CSvO/MmpkgUZlHDfD2CvEvuiOms+Akrf+tqJceLI2PidUb9hlO4yhOPtRa8M9R9GGXOmRQuBykB4U8Ci/dhQ3551Ii5Ogb4Bax0Fzjg7AWDu/JVu1oOhT6Bd48dtBDbejVjd+2fMV79YtH4iZyDHy6EZRbZFAALTzbkb+niO9+B0XXDF8Pws+fq4SmU0Mq1yiW+KNHpuwRZcuTtpzhDIFkEDYYZTi8Lu70Q9Eh90Sh5Q4iDpvUSxXE7VeA92bpX0WauYR1tppJSKp10MUXCRVLMqO4ttXSd0zeJfSPSqwympHkT63IoHtwvj6mcztKf0NDZ2dfhUtAc0ufybPozlCwRcP8oGH8mA22/LsPxn7mZNbzwoGI4ETTmbVVl8D0tTERG5S5wYWqogWyDvfNf/p/RVXjq5xzRxZdVKcj4XGd3sJAfcqzmMh0Xy16TPpDLGlFKqOaU9qMib/9DFrnNcAewjs3EsZck/3uhjv9vbNCWOEt77DyIT5N31Lx0yJ5XCxZYLc92MkSQZ3It4w+LbVqB7bM+aHav+/BNrTWIakSjsITo3ers3zRstGWlxLBK3xljZE1i34quCorVOpNeGwiwQTXja3s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
