travis:
  secure:
    BINSTAR_TOKEN: J2Mtu8Ria410n33KnW4HHapo0TSBFy2C8w2ETBmkXQwOkm0Vw8tk9gi4Y+TB9KFoURzHtJfa+IU7mKjtOJMuT0PxGqoHEV/AwsQjVE6H8hxZPxW7mYrWjr0YNaGADA6rj7QOhqXfPPQOgjc+Vq8JSOcExTc2cU+g0uC5TNpmTVJei/XMOB3c2+4qnjQfOsztMtILZ2OORF87CcpKijEeWlj+R2HdFaPpgU1F5xtcUFyXdYuLCKBRWF8kJEQevwEe+m0CBWgerFLgkWC+LLCLl0kC/g+N5AYY6taticOxxB4ieQcO8FKIjS1AMYqEMz7Qpgirxx08wKx61JpyRxRob9CyFxsXMQUW8zq/3kIspkCuaRXCqrUwuRKP+W0/vgExYWWBFShUM1H/JjAu2FafTZ0McuIcUFAiQ7CQ4ZEw94PCGDx9hjD04RrGmeOLoEURg+aa3Yht18GC3VBxZsZ9cDsJSuuVik14CV6aKoLqeTDcjtlDQTyFcVKoHZnhqCQEe9Dwh+/NL4svXPXEGpIWHNiYjvkUv5T3gd1YlHs0TmF3Cx98v72JHQbm/VWeS6oUOF9BJ5/CB9eIhREV1rrtyQGIU6Ds0XusH8xP91RGSEq0R2xty0Co/vwM7iE0iX/TRJYSMpCV5hIU4ZB/PvEChSq7dUaZ3OnOaV8N8WPErNc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
